// <auto-generated />
using Asp_Document_Reader.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asp_Document_Reader.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220408184604_Teste")]
    partial class Teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Asp_Document_Reader.Shared.MenuItem", b =>
                {
                    b.Property<int>("RotinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GER_Rotina_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RotinaId"), 1L, 1);

                    b.Property<bool>("Acess")
                        .HasColumnType("bit")
                        .HasColumnName("acesspadm");

                    b.Property<string>("Auxiliar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("paramauxiliar");

                    b.Property<string>("DescMenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescMenu");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("icone");

                    b.Property<string>("Janela")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("janela");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("GER_Menu_ID");

                    b.Property<int>("OrdemMenu")
                        .HasColumnType("int")
                        .HasColumnName("OrdemMenu");

                    b.Property<int>("OrdemRotina")
                        .HasColumnType("int")
                        .HasColumnName("OrdemRotina");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rota");

                    b.Property<string>("Rotina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescRotina");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.HasKey("RotinaId");

                    b.ToTable("viewGer_Menu");
                });
#pragma warning restore 612, 618
        }
    }
}
